### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user03",
  "userName": "코알라",
  "userPass": "pass03",
  "userRole": "ALL"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "userId": "user03",
  "userPass": "pass03"
}

### GET 요청
GET http://localhost:8080/test
Authorization: BEARER eyJkYXRlIjoxNzE2Nzg5Mjg2NTExLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJvaGdpcmFmZmVycyB0b2tlbiA6IDIiLCJ1c2VyTmFtZSI6Iuy9lOyVjOudvCIsInVzZXJSb2xlIjoiQURNSU4iLCJleHAiOjE3MTY4NzU2ODYsInVzZXJJZCI6InVzZXIwMiJ9.H2Ffw-jxsGQ3mF3LElclgSkJzXkAtQbuySGBWpcT7qE

### POST 요청
POST http://localhost:8080/test
Authorization: BEARER eyJkYXRlIjoxNzE2Nzg5MTEwMTQ0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJvaGdpcmFmZmVycyB0b2tlbiA6IDEiLCJ1c2VyTmFtZSI6Iuy9lOyVjOudvCIsInVzZXJSb2xlIjoiVVNFUiIsImV4cCI6MTcxNjg3NTUxMCwidXNlcklkIjoidXNlcjAxIn0.zIndsMAFwwr5S93q4LvDD-LUxEy1XPsabewAsvPkI5I